/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDiagnosisRouteImport } from './routes/_authenticated/diagnosis'
import { Route as AuthenticatedMentorRouteImport } from './routes/_authenticated/mentor'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedResumeRouteImport } from './routes/_authenticated/resume'
import { Route as AuthenticatedRoadmapRouteImport } from './routes/_authenticated/roadmap'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiagnosisRoute = AuthenticatedDiagnosisRouteImport.update({
  id: '/diagnosis',
  path: '/diagnosis',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMentorRoute = AuthenticatedMentorRouteImport.update({
  id: '/mentor',
  path: '/mentor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResumeRoute = AuthenticatedResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRoadmapRoute = AuthenticatedRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diagnosis': typeof AuthenticatedDiagnosisRoute
  '/mentor': typeof AuthenticatedMentorRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/resume': typeof AuthenticatedResumeRoute
  '/roadmap': typeof AuthenticatedRoadmapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diagnosis': typeof AuthenticatedDiagnosisRoute
  '/mentor': typeof AuthenticatedMentorRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/resume': typeof AuthenticatedResumeRoute
  '/roadmap': typeof AuthenticatedRoadmapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/diagnosis': typeof AuthenticatedDiagnosisRoute
  '/_authenticated/mentor': typeof AuthenticatedMentorRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/resume': typeof AuthenticatedResumeRoute
  '/_authenticated/roadmap': typeof AuthenticatedRoadmapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/diagnosis'
    | '/mentor'
    | '/onboarding'
    | '/resume'
    | '/roadmap'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/diagnosis'
    | '/mentor'
    | '/onboarding'
    | '/resume'
    | '/roadmap'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/diagnosis'
    | '/_authenticated/mentor'
    | '/_authenticated/onboarding'
    | '/_authenticated/resume'
    | '/_authenticated/roadmap'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diagnosis': {
      id: '/_authenticated/diagnosis'
      path: '/diagnosis'
      fullPath: '/diagnosis'
      preLoaderRoute: typeof AuthenticatedDiagnosisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mentor': {
      id: '/_authenticated/mentor'
      path: '/mentor'
      fullPath: '/mentor'
      preLoaderRoute: typeof AuthenticatedMentorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resume': {
      id: '/_authenticated/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof AuthenticatedResumeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roadmap': {
      id: '/_authenticated/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof AuthenticatedRoadmapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDiagnosisRoute: typeof AuthenticatedDiagnosisRoute
  AuthenticatedMentorRoute: typeof AuthenticatedMentorRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedResumeRoute: typeof AuthenticatedResumeRoute
  AuthenticatedRoadmapRoute: typeof AuthenticatedRoadmapRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDiagnosisRoute: AuthenticatedDiagnosisRoute,
  AuthenticatedMentorRoute: AuthenticatedMentorRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedResumeRoute: AuthenticatedResumeRoute,
  AuthenticatedRoadmapRoute: AuthenticatedRoadmapRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
